### ISSUE TITLE
using it without magisk

### ISSUE THREAD

**Issue by ham3dt** [Magisk-Modules-Repo/sysconfig-patcher#2]
hi, is there anyway to use this patch without magisk?

**Comment by VR-25** [comment]
# Run this script to patch your system

mount -o remount,rw /system
for i in /system/sysconfig/*; do
  if [[ -f $i ]]; then
    grep -Eq '<allow-in-power-save|<allow-in-data-usage-save' "$i" && \
	  sed -i '/allow-in-.*-save/s/<a/<!-- a/' $file
  fi
done
sed -i '/.volta/s/<!-- a/<a/'  /system/sysconfig/google.xml
